---
driver:
  name: ec2

provisioner:
  name: chef_solo

transport:
 ssh_key: ~/demonops/rreilly.pem

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    driver:
      user_data: "#!hostname sensu"
    run_list:
      - recipe[demonops::default]
    attributes:
