---
driver:
  name: ec2

provisioner:
  name: chef_solo

transport:
 ssh_key: ~/demonops/rreilly.pem

platforms:
  - name: ubuntu-16.04
    image_id: ami-4ba6b85c
    instance_type: m4.large

suites:
  - name: default
    driver:
      user_data: "q
      #!/bin/bash sudo /bin/hostname sensu"
    run_list:
      - recipe[demonops::default]
    attributes:
      demonops:
        testmode: 1
        hostname: 'sensu'
