---
driver:
  name: ec2

provisioner:
  name: chef_solo

transport:
 ssh_key: ~/demonops/rreilly.pem

platforms:
  - name: ubuntu-16.04
    image_id: ami-4ba6b85c

suites:
  - name: default
    driver:
      user_data: "#!sudo /bin/hostname sensu"
    run_list:
      - recipe[demonops::default]
    attributes:
