---
driver:
  name: ec2
  subnet_id: subnet-48e58e44
  instance_type: t2.large
  aws_ssh_key_id: rreilly-ec2
  associate_public_ip: false

provisioner:
  name: chef_solo

transport:
  ssh_key: ~/.ssh/rreilly.pem

platforms:
  - name: ubuntu-17.04
    image_id: ami-fb310580
    tags: '{"created-by" => "rreilly", "name" => "test-kitchen"}'



suites:
  - name: default
    driver:
      user_data: "#!/bin/bash sudo /bin/hostname sensu"
    run_list:
      - recipe[demonops::default]
    attributes:
      demonops:
        testmode: 1
        hostname: 'sensu'
