---
driver:
  name: ec2

provisioner:
  name: chef_solo

transport:
 ssh_key: ~/.ssh/rreilly.pem

platforms:
  - name: ubuntu-14.04
    instance_type: m4.large

suites:
  - name: default
    driver:
      user_data: "#!/bin/bash sudo /bin/hostname sensu"
    run_list:
      - recipe[demonops::default]
    attributes:
      demonops:
        testmode: 1
        hostname: 'sensu'
